### ISSUE TITLE
Logging - channel 

### ISSUE THREAD

**Issue by Ruslan-B** [ckarcz/CrazyflieDotNet#13]
Hello @ckarcz 

This not an issue, more information enquiry. Do you have any information or other pointers how to get logging information form Crazyflie, like exact battery level or actual yaw, pitch, roll information?
I just know it is possible via official python api.

Thank you in advance,
Ruslan

**Comment by ckarcz** [comment]
Hi Ruslan,

At the time I did not implemented the log request packet because the documentation was super limited in this area.

We'd have to create a packet class that requests logs/metrics from the copter. This class would generate the correct packet payload and header. 

Look at the documentation wiki for CRTP logging here
https://wiki.bitcraze.io/doc:crazyflie:crtp:log <https://wiki.bitcraze.io/doc:crazyflie:crtp:log>

The headers are already implemented. The payload byte structure is documented in the wiki link above.

If you make any progress, let me know and we can update the repo.

Cheers,
Chris

**Comment by Ruslan-B** [comment]
Chris, thank you! In case I have it working I'll contribute it for sure.
